config/routes.rb
Fragment::Application.routes.draw do

  get 'relationships/create'

  get 'relationships/destroy'

  root 'static_pages#home'
  match '/help',  to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'

  resources :users  #これでRESTfulアクション全て実装
  resources :microposts, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]

  resources :relationships, only: [:create, :destroy]

  match '/signup',   to: 'users#new', via: 'get'

  match '/signin',   to: 'sessions#new',     via: 'get'
  match '/signout',  to: 'sessions#destroy', via: 'delete'

  resources :users do
    member do
      get :following, :followers
    end
  end

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>

    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li id="error_list"><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts_area">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>"> <!--partial collectionを使用しているので、@feed_items配列オブジェクトの入ったfeed_item変数が勝手に作成される-->
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="feed_content"><%= feed_item.content %></span>
    <% if current_user?(feed_item.user) %>
      <%= link_to "delete",feed_item , method: :delete, data: {confirm: "You sure?"}, title: feed_item.content %> <%# feed_item または micropost_path(feed_item.id) %>
    <% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Write contents...", size: "40x7" %>
    <div class="submit_button">
      <%= f.submit "Post", class: "btn btn-sm btn-default" %>
    </div>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
 <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
      <a href="<%= user_path(current_user) %>">
        <%= gravatar_for current_user %>
      </a>
    </div>

    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
        <div class="user_info_name">
        <% if @professions.any? %> <%# if @professions.any?だとエラーになる %>
          <% @professions.each do |profession| %>
            <%= image_tag("#{profession.profession_name}.png", size: "35x35", alt: "profession_icon") %><%#= current_user.name %>
          <% end %>
        <% end %>
        </div>

        <span>
          <%= link_to "Profile", user_path(current_user) %>
        </span>
        <span>
          <%= pluralize(current_user.microposts.count, "micropost") %> now.
        </span>
        <div class="profile_comment">
        </div>
    </div>
</div>