config/routes.rb
Fragment::Application.routes.draw do

  get 'relationships/create'

  get 'relationships/destroy'

  root 'static_pages#home'
  match '/help',  to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'

  resources :users  #これでRESTfulアクション全て実装
  resources :microposts, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]

  resources :relationships, only: [:create, :destroy]

  match '/signup',   to: 'users#new', via: 'get'

  match '/signin',   to: 'sessions#new',     via: 'get'
  match '/signout',  to: 'sessions#destroy', via: 'delete'

  resources :users do
    member do
      get :following, :followers
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">

  <small>
    <a href="http://momozono-hello.tumblr.com/">Momozono Works</a>
    by Momozono.
  </small>

  <nav>

  </nav>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Comedicals", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav pull-right" id="header">
          <li><%= link_to "Home", root_path, id: "header" %></li>
          <li><%= link_to "Help", help_path, id: "header" %></li>

          <% if signed_in? %>
            <li><%= link_to "Users", users_path, id: "header" %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="account">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user, id: "dropdown-color" %></li>
                <li><%= link_to "Settings", edit_user_path(current_user), id: "dropdown-color" %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete", id: "dropdown-color" %>
                </li>
              </ul>
            </li>
            <% else %>
              <li><%= link_to "Sign in", signin_path, id: "dropdown-color" %></li>
            <% end %>

        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= generate_title(yield(:title)) %></title>
  <link href='http://fonts.googleapis.com/css?family=Nunito' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>

<body>
  <%= render 'layouts/header' %>

  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
      <%= yield %>
  </div>

  <div class="container">
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>